WITH sorted AS (
    SELECT 
     e.ID,
     ROW_NUMBER() OVER (ORDER BY e.SIZE_OF_COLONY DESC) AS RANK_,
     count(*) OVER () AS TOTAL
    FROM ECOLI_DATA e
)
SELECT s.ID,
 case 
  WHEN RANK_ <= TOTAL / 4 THEN 'CRITICAL'
  WHEN RANK_ BETWEEN TOTAL / 4 + 1 AND TOTAL / 2 THEN 'HIGH'
  WHEN RANK_ BETWEEN TOTAL / 2 + 1 AND TOTAL / 4 * 3 THEN 'MEDIUM'
  WHEN TOTAL / 4 * 3 <  RANK_ THEN 'LOW'
 END AS COLONY_NAME
FROM sorted s
ORDER BY s.ID ASC;